spring:
  application:
    name: product-catalog
# db config
  datasource:
    url: jdbc:postgresql://localhost:5432/${DB_NAME}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true
# liquidbase config
  liquibase:
    enabled: true
    change-log: classpath:db/changelog/db.changelog-master.xml
# port
server:
  port: 8081
